remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: Advent Of Code
description: Solutions and Write-Ups for my Advent Of Code adventures (mainly in Haskell)
